### PR TITLE
Add grayscale setting to dot filter

### LINKED ISSUE #268: Dot Filter color enabling
Hi there,

I was wondering if there was any way I could retain the input's original color when using the dot filter. By default, it's in black-and-white and there seem to be no parameters to modify it, but if there is something I can change in the source code to keep the original color, I'd like to do so.

Thanks!

### PR DESCRIPTION
**Pull request by vikpe**
Closes #268.

[dot_grayscale.webm](https://user-images.githubusercontent.com/1616817/207953950-79be758b-b79e-48c6-aade-924b888b62c2.webm)

### CODE REVIEW

**Comment by vikpe** [comment]
is there any particular reason why the color average is used for grayscale?

most grayscale conversions i've seen use weighted factors per color, e.g. `(0.3 * R) + (0.59 * G) + (0.11 * B)`.

**example** (weighted = left, average = right):
image

**Comment by bigtimebuddy** [comment]
This looks good! I agreed the weighted approach looks better than average. Totally open if you want to add that. Not all these filters are full-featured or of a high quality so likely it's an oversight rather than something intentional.

**Comment by vikpe** [comment]
I think it would make most sense to drop the grayscale setting in dotfilter and have a separate grayscale filter, but that would break backwards compatibility.

**Comment by bigtimebuddy** [comment]
Maybe just add a flag (grayscaleMode) in the constructor use a different fragment shader. Then the next major version we'll use the weighted version instead of the average.

**Comment by vikpe** [comment]
Good for now :)

**Review by bigtimebuddy — APPROVED** [review]

**Pull request merged**
